freebsd_11_task:
  freebsd_instance:
    image: freebsd-11-2-release-amd64
  install_script:
    - pkg install -y cmake llvm ninja py36-pip python3
    - python3 -m pip install lit
  script:
    - LIBPREOPEN_SRC_DIR=$(pwd)/lib LIBPREOPEN_BUILD_DIR=$(pwd)/build/Debug ci/build.sh Debug

freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  install_script:
    - pkg install -y cmake llvm ninja py36-pip python3
    - python3 -m pip install lit
  script:
    - LIBPREOPEN_SRC_DIR=$(pwd)/lib LIBPREOPEN_BUILD_DIR=$(pwd)/build/Debug ci/build.sh Debug
